project:
  type: website

website:
  title: "ISSS608-VAA-mh"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - href: hands_on_1.qmd
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class exercise 1: Tableau Visualisation"
          href: https://public.tableau.com/app/profile/minghao.liang/viz/inclass-exercise-1/Dashboard1
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

