project:
  type: website
website:
  title: "ISSS608-VAA-mh"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - href: handson_1.Rmd
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class 1: Tableau Visualisation"
          href: inclass_1.Rmd
    - text: "Take-home Exercise"
      menu:
        - text: "Take-Home exercise 1"
          href: takehome_1.Rmd
    right:
      - href: index.qmd
        text: Home
      - text: Gallery
        href: Gallery.qmd
collections:
  posts:
    categories: true
    categories_metadata: true
    authors_metadata: true
format:
  html:
    theme: solar
    css: styles.css
    toc: true
editor: visual

