project:
  type: website
website:
  title: "Minghao's Data Visualization Archive"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: 'Hands-on Exercise 1'
          href: 'handson_1/handson_1.Rmd'
        - text: 'Hands-on Exercise 2'
          href: 'handson_2/hands_on2.qmd'
        - text: 'Hands-on Exercise 3'
          href: 'handson_3/hands_on3.qmd'
        - text: 'Hands-on Exercise 4'
          href: 'handson_4/handson_4.Rmd'
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class 1: Tableau Visualisation"
          href: 'inclass_1/inclass_1.Rmd'
        - text: "In-Class 2: Interactivity in Tableau"
          href: 'inclass_2/inclass_2.qmd'
        - text: "In-Class 3: Exploring Interactivity in R"
          href: 'inclass_3/inclass_3.Rmd'
        - text: "In-Class 4: Plotly"
          href: 'inclass_4/inclass_4.Rmd'
        - text: "In-Class 5: Visual Multivariate Analysis"
          href: 'inclass_5/inclass_5.Rmd'
        - text: "In-Class 6: Time Series Data Visualization"
          href: 'inclass_6/inclass_6.Rmd'
    - text: "Take-home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: 'takehome_1/takehome_1.Rmd'
        - text: "Take-Home Exercise 2"
          href: 'takehome_2/takehome_2.Rmd'
        - text: "Take-Home Exercise 3"
          href: 'takehome_3/takehome_3.Rmd'
        - text: "Take-Home Exercise 4"
          href: 'takehome_4/takehome_4.Rmd'
    - text: "Project: Hotel Data Visualization"
      href: https://visual-analytics-2023jan-group1.netlify.app 
    right:
      - href: index.qmd
        text: Home
      - text: Gallery
        href: Gallery.qmd
collections:
  posts:
    categories: true
    categories_metadata: true
    authors_metadata: true
format: 
  html:
    page-layout: full
    theme: solar
    css: styles.css
    toc: true
editor: visual

