---
title: "In-Class Exercise 8"
categories: in-class exercise
description: |
  Visualize network graph data with R.
author:
  - name: Liang Minghao
    affiliation: SMU, MITB
    affiliation_url: https://scis.smu.edu.sg/master-it-business
date: "11 Mar, 2023"
preview: inclass_7_1.jpg
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

# Load Packages

```{r}
pacman::p_load(igraph, tidygraph, ggraph, 
               visNetwork, lubridate, clock,
               tidyverse, graphlayouts)
```

# Load Data

```{r}
GAStech_nodes <- read_csv("/Users/minghaooo/mtlmh34/ISSS608-VAA-mh/Data/s8/GAStech_email_node.csv")
GAStech_edges <- read_csv("/Users/minghaooo/mtlmh34/ISSS608-VAA-mh/Data/s8/GAStech_email_edge-v2.csv")

glimpse(GAStech_nodes)
glimpse(GAStech_edges)
```

# Data Preprocessing

```{r}
GAStech_edges <- GAStech_edges %>%
  mutate(SendDate = dmy(SentDate)) %>%     #set datatype of SentDate to Date
  mutate(Weekday = wday(SentDate,          #extract days in a week
                        label = TRUE,
                        abbr = FALSE))

# aggreate number of emails between 2 nodes on each weekday
GAStech_edges_aggregated <- GAStech_edges %>%
  filter(MainSubject == "Work related") %>%
  group_by(source, target, Weekday) %>%
    summarise(Weight = n()) %>%
  filter(source!=target) %>%
  filter(Weight > 1) %>%
  ungroup()
```

# Create Graph


```{r}
GAStech_graph <- tbl_graph(nodes = GAStech_nodes,
                           edges = GAStech_edges_aggregated, 
                           directed = TRUE)
GAStech_graph
```

# Visualization of networks with modification of layouts, edges and nodes

```{r}
g <- ggraph(GAStech_graph, 
            layout = "nicely") + # Layout
  geom_edge_link(aes(width=Weight),  # Use weight as the width of edge
                 alpha=0.2) +
  scale_edge_width(range = c(0.1, 5)) +
  geom_node_point(aes(colour = Department),  # Use Department as different colours of nodes
                  size = 3)

g + theme_graph()
```

# Facet Graphs

```{r}
set_graph_style() 

g <- ggraph(GAStech_graph, 
            layout = "nicely") + 
  geom_edge_link(aes(width=Weight), 
                 alpha=0.2) +
  scale_edge_width(range = c(0.1, 5)) +
  geom_node_point(aes(colour = Department), 
                  size = 2)
  
g + facet_edges(~Weekday) +                # facet by weekday
  th_foreground(foreground = "grey80",     # create foreground
                border = TRUE) +
  theme(legend.position = 'bottom')
```

# Network Analysis

## Visualizing Centrality
```{r}
g <- GAStech_graph %>%
  mutate(betweenness_centrality = centrality_betweenness()) %>%
  ggraph(layout = "fr") + 
  geom_edge_link(aes(width=Weight), 
                 alpha=0.2) +
  scale_edge_width(range = c(0.1, 5)) +
  geom_node_point(aes(colour = Department,
            size=betweenness_centrality))           # size of nodes = centrality
g + theme_graph()


# Alternative
# g <- GAStech_graph %>%
#   ggraph(layout = "fr") + 
#   geom_edge_link(aes(width=Weight), 
#                  alpha=0.2) +
#   scale_edge_width(range = c(0.1, 5)) +
#   geom_node_point(aes(colour = Department, 
#                       size = centrality_betweenness()))
# g + theme_graph()

```

## Visualizaing Community

```{r}
g <- GAStech_graph %>%
  mutate(community = as.factor(group_edge_betweenness(weights = Weight, directed = TRUE))) %>%
  ggraph(layout = "fr") + 
  geom_edge_link(aes(width=Weight), 
                 alpha=0.2) +
  scale_edge_width(range = c(0.1, 5)) +
  geom_node_point(aes(colour = community))  

g + theme_graph()
```

# Interative Network Graph

## Prepare Data

```{r}
GAStech_edges_aggregated <- GAStech_edges %>%
  left_join(GAStech_nodes, by = c("sourceLabel" = "label")) %>%
  rename(from = id) %>%
  left_join(GAStech_nodes, by = c("targetLabel" = "label")) %>%
  rename(to = id) %>%
  filter(MainSubject == "Work related") %>%
  group_by(from, to) %>%
    summarise(weight = n()) %>%
  filter(from!=to) %>%
  filter(weight > 1) %>%
  ungroup()
```

## Working with layout

```{r}
visNetwork(GAStech_nodes,
           GAStech_edges_aggregated) %>%
  visIgraphLayout(layout = "layout_with_fr") 
```


## Group Nodes

```{r}
GAStech_nodes <- GAStech_nodes %>% rename(group = Department)

visNetwork(GAStech_nodes,
           GAStech_edges_aggregated) %>%
  visIgraphLayout(layout = "layout_with_fr") %>%
  visLegend() %>%
  visLayout(randomSeed = 123)
```


## Interactivity

```{r}
visNetwork(GAStech_nodes,
           GAStech_edges_aggregated) %>%
  visIgraphLayout(layout = "layout_with_fr") %>%
  visOptions(highlightNearest = TRUE,
             nodesIdSelection = TRUE) %>%
  visLegend() %>%
  visLayout(randomSeed = 123)
```

