---
title: "In-Class Exercise 3"
categories: in-class exercise
description: |
  Exploring interactivity in visual analytics using R.
author:
  - name: Liang Minghao
    affiliation: SMU, MITB
    affiliation_url: https://scis.smu.edu.sg/master-it-business
date: "Jan 28 2023"
date modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
preview: 
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

## Installing and loading R packages

Two packages will be installed and loaded: tidyverse and ggiraph.

```{r}
pacman::p_load(ggiraph,tidyverse)
```

## Importing data

```{r}
exam_data <- read_csv('../Data/Exam_data.csv')
```

## Visualization
### Dotplot using ggplot2
```{r}
ggplot(exam_data,
       aes(x=MATHS)) +
  geom_dotplot(dotsize = .5)
```
### Interactive dotplot using girafe
Notice student id is shown when it is being hovered on.
```{r}
exam_data$tooltip <- c(paste0(
  "Name = ", exam_data$ID,
  "\t Class = ", exam_data$CLASS,
  "\t Grade = ", exam_data$MATHS))

p <- ggplot(data=exam_data, 
       aes(x = MATHS)) +
  geom_dotplot_interactive(
    aes(tooltip = exam_data$tooltip),
    stackgroups = TRUE, 
    binwidth = 1, 
    method = "histodot") +
  scale_y_continuous(NULL, breaks = NULL)
girafe(
  ggobj = p,
  width_svg = 6,
  height_svg = 6*0.618
)
```

```{r}
```

```{r}
```
