---
title: "In-Class Exercise 5"
categories: in-class exercise
description: |
  R: Visual Multivariate Analysis
author:
  - name: Liang Minghao
    affiliation: SMU, MITB
    affiliation_url: https://scis.smu.edu.sg/master-it-business
date: "Feb 11 2023"
date modified: "`r Sys.Date()`"
format: html
execute: 
  echo: true
  eval: true
  warning: false
preview: 
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Ternary Diagram

### Import libraries and data
```{r}
pacman::p_load(ggtern, plotly, tidyverse)

data <- read_csv('/Users/minghaooo/mtlmh34/ISSS608-VAA-mh/Data/respopagsex2000to2018_tidy.csv')

data
```
### Data wranggling
```{r}
agpop_mutated <- data %>%
  mutate(`Year` = as.character(Year))%>%
  spread(AG, Population) %>%
  mutate(YOUNG = rowSums(.[4:8]))%>%
  mutate(ACTIVE = rowSums(.[9:16]))  %>%
  mutate(OLD = rowSums(.[17:21])) %>%
  mutate(TOTAL = rowSums(.[22:24])) %>%
  filter(Year == 2018)%>%
  filter(TOTAL > 0)
agpop_mutated
```
```{r}
ggtern(data=agpop_mutated,aes(x=YOUNG,y=ACTIVE, z=OLD)) + geom_point()
```
### Added Theme
```{r}
ggtern(data=agpop_mutated, aes(x=YOUNG,y=ACTIVE, z=OLD)) +
  geom_point() +
  labs(title="Population structure, 2015") +
  theme_rgbw()
```

### Interactive
```{r}
label <- function(txt) {
  list(
    text = txt, 
    x = 0.1, y = 1,
    ax = 0, ay = 0,
    xref = "paper", yref = "paper", 
    align = "center",
    font = list(family = "serif", size = 15, color = "white"),
    bgcolor = "#b3b3b3", bordercolor = "black", borderwidth = 2
  )
}

axis <- function(txt) {
  list(
    title = txt, tickformat = ".0%", tickfont = list(size = 10)
  )
}

ternaryAxes <- list(
  aaxis = axis("Young"), 
  baxis = axis("Active"), 
  caxis = axis("Old")
)

plot_ly(
  agpop_mutated,
  # a b c are the 3 variables, text is the tooltip (sub-zone)
  a = ~YOUNG, 
  b = ~ACTIVE, 
  c = ~OLD, 
  text = ~SZ,
  color = I('#DB7365'), 
  type = "scatterternary"
) %>%
  layout(
    annotations = label("Ternary Markers"), 
    ternary = ternaryAxes
  )
```
## Correlation Diagram

### Import libraries and data
```{r}
pacman::p_load(corrplot, tidyverse, ggstatsplot, GGally)
wine <- read_csv("/Users/minghaooo/mtlmh34/ISSS608-VAA-mh/Data/wine_quality.csv")
wine
```

### Correlation Matrix
```{r}
pairs(wine[,2:12])
```
### Drawing the lower corner

```{r}
pairs(wine[,2:12], upper.panel = NULL)

# Drawing upper corner
# pairs(wine[,2:12], lower.panel = NULL)
```

### Including Coefficients

```{r warning = FALSE}
panel.cor <- function(x, y, digits=2, prefix="", cex.cor, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y, use="complete.obs"))
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  txt <- paste(prefix, txt, sep="")
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = cex.cor * (1 + r) / 2)
}

pairs(wine[,2:12], 
      upper.panel = panel.cor)
```

### Using `corrplot`

```{r}
# building correlation matrix
wine.cor <- cor(wine[, 1:11])

corrplot.mixed(wine.cor, 
               #lower corner
               lower = "ellipse", 
               #upper corner
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               tl.col = "blue")
```

### Find highly correlated group

```{r}
corrplot(wine.cor, 
         method = "ellipse", 
         tl.pos = "lt",
         tl.col = "black",
         order="hclust",
         hclust.method = "ward.D",
         addrect = 3)
```
### With Significant Test

```{r}
# sig. test
wine.sig = cor.mtest(wine.cor, conf.level= .95)

#
corrplot(wine.cor,
         method = "number",
         type = "lower",
         diag = FALSE,
         tl.col = "black",
         tl.srt = 45,
         p.mat = wine.sig$p,
         sig.level = .05)
```


